name: Build and Test JupyterLab Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: docker build -t cpp_jupyterlab .

    - name: Run Container
      run: |
        docker run -d --name cpp_test cpp_jupyterlab
        docker exec cpp_test sh -c "jupyter kernelspec list | grep xeus-cling-cpp17"
