name: Test and Publish JupyterLab C++ Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t jupyterlab_cpp .

      - name: Run C++ Notebook Test
        run: |
          docker run -d --name cpp_test -v ${{ github.workspace }}/notebooks/:/workspace/notebooks/ jupyterlab_cpp jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --no-browser
          sleep 10
          docker exec cpp_test jupyter nbconvert --to notebook --execute /workspace/notebooks/cpp_kernel_test.ipynb

      # Extract tag name
      - name: Extract Tag Name
        shell: bash
        run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

      # Login to Docker Hub
      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Push Docker Image with the tag version
      - name: Push Docker Image with the tag version
        if: success()
        run: |
          docker tag jupyterlab_cpp ${{ secrets.DOCKERHUB_USERNAME }}/jupyterlab_cpp:latest
          docker tag jupyterlab_cpp ${{ secrets.DOCKERHUB_USERNAME }}/jupyterlab_cpp:${{ env.TAG_NAME }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/jupyterlab_cpp:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/jupyterlab_cpp:${{ env.TAG_NAME }}
